### ISSUE TITLE
I can't run this

### ISSUE THREAD

**Issue by Marcel0024** [mhavey/mongomovie#1]
I don't understand the instructions. Sorry for my incompetence

**Comment by mhavey** [comment]
Let me help. Do you have an environment with MongoDB installed? Are you able to download the files from IMDB?

**Comment by Marcel0024** [comment]
Yes i downloaded all the files and placed them in imdb.

Java home should be pointed to a JRE,correct?
So like this?
JAVA_HOME=C:\Program Files (x86)\Java\jre1.8.0_91\bin
ETL_HOME=C:\Code\MongoMovies\mongomovie-master\lib
CLASSPATH=$
ETL_HOME/imdbetl.jar:$ETL_HOME/log4j-1.2.17.jar:$ETL_HOME/mongo-java-driver-2.11.4.jar

Is that correct?
Yes i have mongodb installed.

**Comment by mhavey** [comment]
From your note it looks like you are on a Windows platform but are trying
to use one of the UNIX shell scripts. To run the ETL controller, use
mongomovie/bin/etl/controller.cmd file.
Edit the file to set your JAVA_HOME correctly, as shown below. Then open a
command prompt, cd to the bin\etl directory and run controller.

setlocal

title controller
set JAVA_HOME=c:\Program Files\Java\jre1.8.0_91
set ETL_HOME=....\lib

set
CLASSPATH=%ETL_HOME%\imdbetl.jar;%ETL_HOME%\log4j-1.2.17.jar;%ETL_HOME%\mongo-java-driver-2.11.4.jar

"%JAVA_HOME%\bin\java" -Xms256m -Xmx1024m
org.jude.bigdata.recroom.movies.etl.ETLController
 -props=controller.properties  -clean=none -jobs=all -log4j=log4j.properties

pause

endlocal

**Comment by mhavey** [comment]
I have not tested this carefully on a Windows platform, so please let me
know how it goes and if you run into any issues.

**Comment by mhavey** [comment]
A few more changes for Windows:
1. Before running ETL job, edit mongomovie/bin/etl/controller.properties.
   Set IMDBPath with backslashes, as shown. Also edit MongoHost and MongoPort
   if necessary.
   MongoHost=localhost
   MongoPort=27017
   MongoDB=movies
   IMDBPath=....\imdb
2. Once ETL job is complete, if you want to run the queries in the mongo
   shell, open a command prompt and cd to the mongomovie/src/queries folder. Then
   run the mongo shell:

<fulll_path_of_mongo>\bin\mongo --shell mongoqueries.js
