### ISSUE TITLE
Can not populate all collection

### ISSUE THREAD

**Issue by karthikmr147** [mhavey/mongomovie#2]
I have been successful in setting up and getting this run. Everything seems working fine, there are no errors on the controller.log. There are lots of rejects which are expected. But after the end of the job, I do not see any data in contributor, role collections. The only collection which has data is movie. It will be great if somebody can put some light here . 

Thanks in advance

**Comment by mhavey** [comment]
Let's start with this:

- When did you obtain the IMDB data files? Can you send me a file listing showing the file sizes of these files. 
- How many rejects did you get? Can you attach the reject logs.

**Comment by karthikmr147** [comment]
I appreciate your quick reply. Thank you. I figured it out, i was not running all the controller shell. Now that I have loaded every collection, I am trying to run the queries. I do not get any results for the in the query shell. However when I check the collection through mongoshell , there are data. Do you have any comment on this ?

**Comment by mhavey** [comment]
Happy to hear you got the data loaded. Regarding not seeing results for queries, are you starting the mongo shell using the movieshell.sh script? What happens when you run the following:

getEpisodes("\"The Good Wife\" (2009)")

**Comment by karthikmr147** [comment]
I have ./mongod server running. And I will connect to this server from the movie shell.sh which gives me a shell to run the javascript functions. The javascript file seems not connecting to the server and pulling the data

**Comment by karthikmr147** [comment]
I figure this out too. I need to switch the DB to movies. It works like a charm :) Thank you very much for the detailed write up.

**Comment by mhavey** [comment]
Happy to hear that. Please let me know if you have further issues, and if you have any comments to share, post them to the Packt article.
